"""Emit a LaTeX-ready summary table from the latest sweep JSONs.

For each (baseline, cell) pair the table reports:
  - n (rep count)
  - deep% with Wilson 95% CI
  - shallow%
  - wrong%
  - descended%
  - mean wall-time

Output is a `tabular` block; wrap in `\\begin{table}` in the paper.

Usage:
  python paper/latex_table.py --benchmarks pf_anon_write \\
      --perturbations p1_thp_off p14_madvise_storm p7_taskset_oversubscribe \\
      --baselines B0 B0.5 B1 B2 > paper/tables/headline.tex
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
from glob import glob
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SWEEPS = REPO / "results" / "sweeps"


def wilson_ci(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    denom = 1.0 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = (z / denom) * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return (max(0.0, centre - half), min(1.0, centre + half))


def latest_sweep(baseline: str, bench: str, pert: str) -> dict | None:
    best_mt = -1.0
    best = None
    for fp in glob(str(SWEEPS / "*.json")):
        try:
            d = json.load(open(fp))
        except Exception:
            continue
        if (d.get("baseline") == baseline and d.get("benchmark") == bench
                and d.get("perturbation") == pert):
            mt = os.path.getmtime(fp)
            if mt > best_mt:
                best_mt, best = mt, d
    return best


PERT_LABEL = {
    "p1_thp_off": r"\textsc{p1\_thp\_off}",
    "p4_drop_caches": r"\textsc{p4\_drop\_caches}",
    "p6_sched_idle": r"\textsc{p6\_sched\_idle}",
    "p7_taskset_oversubscribe": r"\textsc{p7\_taskset\_oversubscribe}",
    "p10_thp_aggressor": r"\textsc{p10\_thp\_aggressor}",
    "p11_force_compaction": r"\textsc{p11\_force\_compaction}",
    "p12_dd_io": r"\textsc{p12\_dd\_io}",
    "p13_netem_loopback": r"\textsc{p13\_netem\_loopback}",
    "p14_madvise_storm": r"\textsc{p14\_madvise\_storm}",
    "p20_llm_aggressor": r"\textsc{p20\_llm\_aggressor}",
}


def fmt_pct_ci(k: int, n: int) -> str:
    if n == 0:
        return r"\textemdash"
    pct = 100.0 * k / n
    lo, hi = wilson_ci(k, n)
    return f"{pct:.0f}\\%~[{100*lo:.0f},{100*hi:.0f}]"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--benchmarks", nargs="+", required=True)
    ap.add_argument("--perturbations", nargs="+", required=True)
    ap.add_argument("--baselines", nargs="+", default=["B0", "B0.5", "B1", "B2"])
    args = ap.parse_args()

    print(r"% Generated by paper/latex_table.py -- do not hand-edit")
    print(r"\begin{tabular}{l l r r r r r r}")
    print(r"\toprule")
    print(r"baseline & cell & n & deep\% [95\% CI] & shallow\% & wrong\% & descended\% & wall (s) \\")
    print(r"\midrule")
    for b in args.baselines:
        first_in_baseline = True
        for bench in args.benchmarks:
            for pert in args.perturbations:
                d = latest_sweep(b, bench, pert)
                if d is None:
                    continue
                reps = d.get("reps", [])
                n = len(reps)
                if n == 0:
                    continue
                deep = sum(1 for r in reps if r.get("score") == 1.0)
                shal = sum(1 for r in reps if r.get("score") == 0.5)
                wrong = sum(1 for r in reps if r.get("score") == 0.0)
                desc = sum(1 for r in reps if r.get("descents"))
                walls = [r.get("wall_s", 0.0) or 0.0 for r in reps]
                wmean = sum(walls) / max(len(walls), 1)
                wstd = math.sqrt(sum((w - wmean) ** 2 for w in walls)
                                  / max(len(walls), 1))
                cell = PERT_LABEL.get(pert, pert.replace('_', r'\_'))
                bcol = b if first_in_baseline else ""
                first_in_baseline = False
                print(f"{bcol:<8s} & {cell} & {n} & "
                      f"{fmt_pct_ci(deep, n)} & "
                      f"{100*shal/n:.0f}\\% & "
                      f"{100*wrong/n:.0f}\\% & "
                      f"{100*desc/n:.0f}\\% & "
                      f"{wmean:.0f}$\\pm${wstd:.0f} \\\\")
        if not first_in_baseline:
            print(r"\midrule")
    print(r"\bottomrule")
    print(r"\end{tabular}")
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
